services:

  # DEV
  customer-app-dev:
    build: .
    container_name: customer-app-dev
    ports:
      - "8081:8081"
    environment:
      DB_HOST: customer-db-dev
      DB_NAME: customerdb
      DB_USER: customer
      DB_PASSWORD: devpass
    depends_on:
      - customer-db-dev
    networks:
      - customer-dev-net

  customer-db-dev:
    image: postgres:17-alpine
    container_name: customer-db-dev
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: devpass
    networks:
      - customer-dev-net
    volumes:
      - customer-dev-db-data:/var/lib/postgresql/data


  # UAT
  customer-app-uat:
    build: .
    container_name: customer-app-uat
    ports:
      - "8082:8081"
    environment:
      APP_ENV: UAT
      APP_VERSION: "1.0"
      DB_HOST: customer-db-uat
      DB_NAME: customerdb
      DB_USER: customer
      DB_PASSWORD: uatpass
    depends_on:
      - customer-db-uat
    networks:
      - customer-uat-net

  customer-db-uat:
    image: postgres:17-alpine
    container_name: customer-db-uat
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: uatpass
    networks:
      - customer-uat-net
    volumes:
      - customer-uat-db-data:/var/lib/postgresql/data


  # PROD
  customer-app-prod:
    build: .
    container_name: customer-app-prod
    ports:
      - "8083:8081"
    environment:
      APP_ENV: PRODUCTION
      APP_VERSION: "1.0"
      DB_HOST: customer-db-prod
      DB_NAME: customerdb
      DB_USER: customer
      DB_PASSWORD: prodpass
    depends_on:
      - customer-db-prod
    networks:
      - customer-prod-net

  customer-db-prod:
    image: postgres:17-alpine
    container_name: customer-db-prod
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: prodpass
    networks:
      - customer-prod-net
    volumes:
      - customer-prod-db-data:/var/lib/postgresql/data


# NETWORKS
networks:

  customer-dev-net:
    name: customer-dev-net

  customer-uat-net:
    name: customer-uat-net

  customer-prod-net:
    name: customer-prod-net


# VOLUMES
volumes:

  customer-dev-db-data:

  customer-uat-db-data:

  customer-prod-db-data: